### PR TITLE
(Fix) Numbers and token names breaking

### LINKED ISSUE #532: Price are displayed weirdly
Can we please get a fix for the prices? 
If the tokenname is longer, usually prices are displayed very strangely.

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #532

Cherry picked some code from what I'm doing for #152. I don't think it will break anything, and it should fix this problem.

### CODE REVIEW

**Comment by josojo** [comment]
Hm... in my browser it looks like that:
image
I think the numbers are too bold and orange in the circle looks weird. 
I actually liked it much better before..
image

**Comment by franzmoca** [comment]
Hello I am from the SNAFU team, we are currently doing an auction ending in less than 2 days and this issue is affecting us greatly.
Could you merge this PR as soon as possible?
Thanks a lot!

**Comment by gabitoesmiapodo** [comment]
> Hm... in my browser it looks like that:
> image
> I think the numbers are too bold and orange in the circle looks weird.
> I actually liked it much better before..
> image

Yeah, that's how it looks in the [latest designs](https://www.figma.com/file/hapgMbgd2Zo5NFZDNfbogQ/Gnosis-Auction-Feedback?node-id=501%3A2).

Anyway, if this fixes the problem with the numbers maybe you can merge it and we can talk about the circle later.

**Review by josojo — APPROVED** [review]
Okay, let's merge it for the ongoing sale

**Pull request merged**
