### PR TITLE
(Feature) Add more information to auctions

### LINKED ISSUE #152: Add more auction information
In order to better provide information to the user about the current status of the auction, I propose to add a small section with these details:

- Current estimated price
- Current estimated funds raised
- Current estimated tokens sold (could also be implemented as a progress bar)

I'm not sure where is the appropriate place to add this.
One solution is to add this instead of the chart, and move the chart into a modal so users on see it on a much larger scale.
What are your thoughts?

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #152

This still needs some programming to fetch the data for the extra details (hence the draft status). I think @hpmaxi  or @josojo  could implement that?

It should look like these:

May-07-2021 10-55-25

Screen Shot 2021-05-07 at 10 49 41
Screen Shot 2021-05-07 at 10 50 51
Screen Shot 2021-05-07 at 10 51 04
Screen Shot 2021-05-07 at 10 51 11
Screen Shot 2021-05-07 at 10 51 22
Screen Shot 2021-05-07 at 10 51 30

### CODE REVIEW

**Comment by josojo** [comment]
Thanks! I will continue from here..

**Review by josojo — APPROVED** [review]

**Comment by henrypalacios** [comment]
Is anyone else experiencing this problem in mobile view?

WhatsApp Image 2021-05-18 at 15 51 30

**Comment by gabitoesmiapodo** [comment]
> Is anyone else experiencing this problem in mobile view?
> 
> WhatsApp Image 2021-05-18 at 15 51 30

Hm, that's new. I'll have a look.

**Comment by gabitoesmiapodo** [comment]
https://github.com/gnosis/ido-ux/issues/550#issuecomment-843475261 should be fixed

**Pull request merged**
