### PR TITLE
Media kit

### PR DESCRIPTION
**Pull request by alongoni**
Related to #759 
GA-dark-bg

The media kit was created in Docs section:
https://pr767--idoux.review.gnosisdev.com/#/docs/media-kit

### CODE REVIEW

**Comment by elena-zh** [comment]
HI @alongoni , 
Could we add section names for the 1st 2 images? Something like 'Black background' and 'White background'. What do you think?
image

Thanks

**Comment by josojo** [comment]
Already cool!

**Comment by cmagan** [comment]
@alongoni thanks, looking good!
I tend to think we don't need to show the media kit image multiple times. It is enough to show the png one on the top and then explain we have also a white version available and provide download links to all version in all formats etc

Another important thing is we need to all all the added text:
on top: "Every auction that is done using Gnosis Auction can use this Media kit:"
In the bottom:
"Important notice to auction participants:

Gnosis Auction enables permissionless P2P auctions applying a batch auction mechanism without the need for intermediaries. Auctions are initiated and organised by the auctioneers. Gnosis Auction and GnosisDAO do not control, initiate or organise auctions nor are we involved with the auctioneers. Please do your own due diligence before participating in an auction.
"

**Comment by henrypalacios** [comment]
@alongoni  I liked it, I'm not sure if it's just me, but I see only the first one color with shadow, is that ok?

Selection_307

**Comment by alongoni** [comment]
> @alongoni I liked it, I'm not sure if it's just me, but I see only the first one color with shadow, is that ok?
> 
> Selection_307

Hey @henrypalacios, I've to added a white shadow to this color to differentiate it from the background (same color). The orange and white colors have a dark shadow that maybe is a bit soft.

**Comment by henrypalacios** [comment]
> Hey @henrypalacios, I've to added a white shadow to this color to differentiate it from the background (same color). The orange and white colors have a dark shadow that maybe is a bit soft.

@alongoni And if you use a medium brightness gray, wouldn't it be more uniform for both cases?

**Comment by alongoni** [comment]
Should we merge it? @cmagan

**Review by josojo — APPROVED** [review]
LGMT

**Pull request merged**
