### PR TITLE
auction pending settlement state moved on claim btn

### PR DESCRIPTION
**Pull request by maria-vslvn**
Closes: #542 

error markup was moved to the claim btn title, and the if statement was extended with it. error styles were extended to fit buttons on mobile devices

### CODE REVIEW

**Comment by elena-zh** [comment]
Hi @maria-vslvn , 

according to the #542 issue description Alex suggested to use option 1 with the text 'Waiting for on-chain price calculation' on the button.
Could you please change it?

Thanks.

**Comment by maria-vslvn** [comment]
@elena-zh error msg is updated

**Review by josojo — APPROVED** [review]
Nice, looks so much better and is likely much easier to understand for customers.

Thanks a lot!

If you are making such PRs, it would be great to write a very short note, how these prrs are tested best. E.g. herre, on could write:
For testing:
Visit the following unfinished auction:
https://pr634--idoux.review.gnosisdev.com/#/auction?auctionId=128&chainId=4#topAnchor
\\

**Comment by elena-zh** [comment]
Changes LGTM now. 
Thanks!

**Comment by maria-vslvn** [comment]
conflicts resolved

**Pull request merged**
