### PR TITLE
[issue-375] Coingecko token list failed validation

### PR DESCRIPTION
**Pull request by jarcodallo**
We actually don't need the token symbol so for now, We can just live with the coingecko error.
image

### CODE REVIEW

**Comment by mariano-aguero** [comment]
Thoughts @jarcodallo 
Screenshot_20210331_105343

**Comment by jarcodallo** [comment]
> Thoughts @jarcodallo
> Screenshot_20210331_105343

We depends on a third party token list icons. In this case [the icon](https://assets.coingecko.com/coins/images/2518/thumb/weth.png?1547036627) is to small. when our component mount it in a grid much bigger, the icon looks bad.

**Comment by mariano-aguero** [comment]
Here is the URL
```
https://assets.coingecko.com/coins/images/2518/thumb/weth.png?1547036627 
```

**Comment by jarcodallo** [comment]
> > Thoughts @jarcodallo
> > Screenshot_20210331_105343
> 
> We depends on a third party token list icons. In this case [the icon](https://assets.coingecko.com/coins/images/2518/thumb/weth.png?1547036627) is to small. when our component mount it in a grid much bigger, the icon looks bad.

That particular icon is from [coingecko](https://tokens.coingecko.com/uniswap/all.json):
```json
{"chainId":1,"address":"0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2","name":"WETH","symbol":"WETH","decimals":18,"logoURI":"https://assets.coingecko.com/coins/images/2518/thumb/weth.png?1547036627"}
```

**Comment by mariano-aguero** [comment]
I think we need to think in another options @josojo to use , for moment the PR  improves how errors are displayed and is better than no icon at all, so I approved

**Review by mariano-aguero — APPROVED** [review]

**Comment by gabitoesmiapodo** [comment]
> But why wasn't it shown before like that? Really strange
> 
> @gabitoesmiapodo Did you change anything with the new "default token logo'? Could you take a look?

Nope, I changed nothing about this.

**Comment by jarcodallo** [comment]
> But why wasn't it shown before like that? Really strange
> 
> @gabitoesmiapodo Did you change anything with the new "default token logo'? Could you take a look?

Coingecko changed it.

**Comment by gabitoesmiapodo** [comment]
> https://assets.coingecko.com/coins/images/2518/thumb/weth.png?1547036627

Can we change that for https://assets.coingecko.com/coins/images/2518/small/weth.png ? (notice the `/small/` part instead of `/thumb/`

That may improve things.

Maybe there are other versions too?

**Comment by jarcodallo** [comment]
> https://assets.coingecko.com/coins/images/2518/small/weth.png

Same icon https://assets.coingecko.com/coins/images/2518/thumb/weth.png

**Comment by jarcodallo** [comment]
> > https://assets.coingecko.com/coins/images/2518/thumb/weth.png?1547036627
> 
> Can we change that for https://assets.coingecko.com/coins/images/2518/small/weth.png ? (notice the `/small/` part instead of `/thumb/`
> 
> That may improve things.
> 
> Maybe there are other versions too?

same icon https://assets.coingecko.com/coins/images/2518/thumb/weth.png

**Comment by gabitoesmiapodo** [comment]
> > > https://assets.coingecko.com/coins/images/2518/thumb/weth.png?1547036627
> > 
> > 
> > Can we change that for https://assets.coingecko.com/coins/images/2518/small/weth.png ? (notice the `/small/` part instead of `/thumb/`
> > That may improve things.
> > Maybe there are other versions too?
> 
> same icon https://assets.coingecko.com/coins/images/2518/thumb/weth.png

Yeah, but the `/small/` version is 50x50 instead of 25x25. Not ideal, but it may look a bit less blurry.

**Comment by jarcodallo** [comment]
> > > > https://assets.coingecko.com/coins/images/2518/thumb/weth.png?1547036627
> > > 
> > > 
> > > Can we change that for https://assets.coingecko.com/coins/images/2518/small/weth.png ? (notice the `/small/` part instead of `/thumb/`
> > > That may improve things.
> > > Maybe there are other versions too?
> > 
> > 
> > same icon https://assets.coingecko.com/coins/images/2518/thumb/weth.png
> 
> Yeah, but the `/small/` version is 50x50 instead of 25x25. Not ideal, but it may look a bit less blurry.

That's ok, but we depend on the mapping of the list with the address. I cannot add an "if" only for that address.

**Comment by josojo** [comment]
WE can also switch to coinmaketcap list, if that helps

**Comment by jarcodallo** [comment]
> WE can also switch to coinmaketcap list, if that helps

Yes, we can, maybe [1inch](https://tokens.1inch.eth.link/)?

**Comment by mariano-aguero** [comment]
coingecko uses size small

Screenshot_20210331_115007

**Comment by gabitoesmiapodo** [comment]
> > > > > https://assets.coingecko.com/coins/images/2518/thumb/weth.png?1547036627
> > > > 
> > > > 
> > > > Can we change that for https://assets.coingecko.com/coins/images/2518/small/weth.png ? (notice the `/small/` part instead of `/thumb/`
> > > > That may improve things.
> > > > Maybe there are other versions too?
> > > 
> > > 
> > > same icon https://assets.coingecko.com/coins/images/2518/thumb/weth.png
> > 
> > 
> > Yeah, but the `/small/` version is 50x50 instead of 25x25. Not ideal, but it may look a bit less blurry.
> 
> That's ok, but we depend on the mapping of the list with the address. I cannot add an "if" only for that address.

Haha, yeah, I meant for all the icons. We should use something larger, 25x25 is too small.

But if you can't request it easily it's a moot point.

**Comment by gabitoesmiapodo** [comment]
Whatever service we end up using: see if we can get images at least 70x70px in size. 

That should be the minimum (a bit less - ie: 50x50px- is OK, and a bit more it's OK too).

**Pull request merged**
