### PR TITLE
Feature/804 full token name

### LINKED ISSUE #804: Show full token name in tooltip when it is truncated to 8 symbols
related to #802

auction?auctionId=37&chainId=1

when a token name is truncated to 8 symbols, still it would be nice to show it's full name in tooltip:

Like here:

### PR DESCRIPTION
**Pull request by maria-vslvn**
Closes #804 
labels were sliced throughout the app, full labels left in tooltips

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @maria-vslvn , I did not mean to return full token values in the red label. 
Truncated token label looks good to me. 
I meant to leave a full token value in the tooltip when hover a mouse on the red label in the Claiming Proceeds section: write instead of `oWETHUS` the whole `oWETHUSDC/WETH-20AUG21-3900C` in brackets there. 
image

**Comment by maria-vslvn** [comment]
@elena-zh please check

**Comment by elena-zh** [comment]
Hey @maria-vslvn , 
still there is no full token name (oWETHUSDC/WETH-20AUG21-3900C) in the tooltip 
image

**Comment by maria-vslvn** [comment]
@elena-zh i had cache issues with it, names are cut correctly at mine after hard refresh + clear cache, could you please try to clear cache and let me know the result?

**Comment by elena-zh** [comment]
@maria-vslvn , I cleared all app storage, including cache data. 
The issue is still here
image

**Comment by maria-vslvn** [comment]
@elena-zh check it

**Comment by elena-zh** [comment]
Changes LGTM now. Thanks!

**Pull request merged**
