### PR TITLE
status icons added

### LINKED ISSUE #632: add status icon to pop-up window after tx passes/fails
1. open app
2. open some active auction
3. place an order
4. cancel order

Result: 
Exp.result: It would be good to add icons as it is done here: 

see all actions and use appropriate icon

### PR DESCRIPTION
**Pull request by maria-vslvn**
Closes #632 
status icons were fixed

### CODE REVIEW

**Review by josojo — APPROVED** [review]
Nice looks and works great on desktop

**Comment by elena-zh** [comment]
@maria-vslvn , 
1. Confirmation messages are not auto-closed now after 15 sec
not auto-closed

2. Confirmation messages are hidden under the app header in a mobile device
not visible in a mobile device

**Comment by maria-vslvn** [comment]
@elena-zh fixed

**Comment by elena-zh** [comment]
@maria-vslvn , great job. 
The only one issue I face is that notification messages do not appear on a real iOS (14.6) device  (Android/web works fine)
Could you please take a look at it?

**Comment by maria-vslvn** [comment]
@elena-zh please check

**Comment by elena-zh** [comment]
Great!

**Comment by josojo** [comment]
Thanks @maria-vslvn

**Pull request merged**
