### PR TITLE
Feature/800 cut lbls

### LINKED ISSUE #800: Auction details: issues with long token names
https://gnosis-auction.eth.link/#/auction?auctionId=37&chainId=1%23topAnchor

We need to do:

1. displaying only first 6-8 characters for the token names. -> probably easy
2. make the one bid visible in the chart. -> probably hard

Also, it would be nice to adjust the Auctions table

And a featured auction card (screenshot as an example)

### PR DESCRIPTION
**Pull request by maria-vslvn**
Closes #800 
modified `gettokendisplay` method allAuctions table names cutted as well

### CODE REVIEW

**Comment by josojo** [comment]
image
Could we get the name in the red box also shorted?

**Comment by elena-zh** [comment]
In addition to the issue reported by Alex, some issues from my side: 
1. Auction details overlap mobile widget
image

2. Not an issue, but it would be better, from my perspective, to move a token pair to another row in the Order table list header
another row

@josojo , WDYT?

**Comment by josojo** [comment]
Regarding Elena's points:
1. Let's find a pragmatic solution for this, either lines breaks or shorting the number of letters of the token symbol by 1.
2. If there is an easy solution, let's do it. But not spend more than 2 hours on it.

I hope we can merge this one soon

**Comment by josojo** [comment]
image
We need to also find a fix for these cards.

**Comment by elena-zh** [comment]
LGTM!
@josojo , please take a look whether it looks good to you either as unfortunately I can't see this auction Featured card now.

**Comment by josojo** [comment]
Thanks all. I tested it again. looks good

**Pull request merged**
