### PR TITLE
Use native eth in order placement

### LINKED ISSUE #636: Enable place orders via ETH
Allow users to submit orders with ETH instead of WETH on mainnet and rinkeby

-> Show ETH balances in all interfaces instead of WETH
-> Make sure that the order placement uses the same logic as xdai orders and the right if-branch is used
https://github.com/gnosis/ido-ux/blob/d712b0859991935906105f4b77e9a14df80bd37a/src/hooks/usePlaceOrderCallback.ts#L110

-> Show wrap und unwarp buttons as currently implemented on xdai

### PR DESCRIPTION
**Pull request by hpmaxi**
Closes #636, #660 

Still need to test this. I guess `isTokenWETH` must be improved to works for rinkeby too. 

Also I think I should do something like `useTokenBalancesTreatWETHAsETHonXDAI`.

### CODE REVIEW

**Comment by josojo** [comment]
Nice!
just added the small rest for testing. It works already great. I was able to place an order here:
`auction?auctionId=144&chainId=4#topAnchor`

The unwrap button can be linked to uniswap, instead of honeyswap on mainnet and rinkeby

**Comment by elena-zh** [comment]
Although the pr is in draft, I have taken a look into it. 
Great job! I was able to place an order in ETH. 

However, here are my questions: 
1. When I cancel an order, I do not receive ETH back to my wallet. I get WETH. Is that OK? 
2. Unwrap button navigates to the https://app.honeyswap.org/ which is relevant for xDAI. I think, the link should be changed for Mainnet/Rinkeby networks. As long as tooltips for this button (tooltips are different for ongoing and ended auctions)
image
3. The issue #660 seems to be unfixed. I'm still able to see 'Unwrap' button for ended auctions where I did not participate/disconnected/connected to another network.

Thanks

**Comment by josojo** [comment]
>When I cancel an order, I do not receive ETH back to my wallet. I get WETH. Is that OK?
yes, unfortunately, this is not possible with the current smart contracts

>Unwrap button navigates to the https://app.honeyswap.org/ which is relevant for xDAI. I think, the link should be changed for Mainnet/Rinkeby networks. As long as tooltips for this button (tooltips are different for ongoing and ended auctions)

Yes, unwrap buttons still need to be changed

**Comment by elena-zh** [comment]
> yes, unfortunately, this is not possible with the current smart contracts

@josojo , what do you think about warning a user about this before cancellation? As an example, add a message to the cancellation confirmation pop-up or so.  I can create an enhancement for this case.

**Comment by josojo** [comment]
> > yes, unfortunately, this is not possible with the current smart contracts
> 
> @josojo , what do you think about warning a user about this before cancellation? As an example, add a message to the cancellation confirmation pop-up or so. I can create an enhancement for this case.

good suggestion! let's not do it in this PR, but we can do it later with a new tickett

**Comment by elena-zh** [comment]
Thanks, Alex! I have created #672 enhancement for this case.

**Comment by hpmaxi** [comment]
@josojo @elena-zh Made some changes based on the feedback.

**Comment by elena-zh** [comment]
@hpmaxi , 
Still see Honeyswap + xDAI tokens in tooltips. Unwrap button still redirects to the Honeyswap..

**Comment by josojo** [comment]
Ups, I only fixed the text. I will also fix the link soon

**Review by josojo — APPROVED** [review]

**Comment by elena-zh** [comment]
@josojo , @hpmaxi , 
changes look good to me! Great job, thank you!

**Pull request merged**
