### PR TITLE
Feature/#696 auction table improvmnts

### LINKED ISSUE #696: Auction Table improvements
We can use a table head to reduce the amount of repeated info (see Auction id, Selling, Buying, Status, etc.)

### PR DESCRIPTION
**Pull request by maria-vslvn**
Closes #696 
1. top disclaimer width 100%
2. all auctions table layout updated

### CODE REVIEW

**Comment by elena-zh** [comment]
Hi @maria-vslvn , I have verified the issue. 
Some UI issues: Header column names  should have font size 14 px,  font-weight = normal. 
https://www.figma.com/file/Y7MLpZujRAOFPVkplvA7kV/Gnosis-Auction?node-id=159%3A0

The next case that was discussed in https://github.com/gnosis/ido-ux/issues/696#issuecomment-869597531 is that all tables in the app should look the same. 
Highest volume auctions table looks the same (besides a few UI issues reported in #774), but 'Your orders' grid in an auction details page is not changed.
image

One more point is that table's header is not scrollable. When a user selects 30 items per page, it is not clear to a user what is shown in the table.
https://drive.google.com/file/d/19aov6hyHyUcmTdqvOwYfSeElFkboiRob/view
 I remember, it was an important point for @cmagan in the discussion https://github.com/gnosis/ido-ux/issues/696#issuecomment-870492972

Could you please fix these issues?

Thanks

**Comment by elena-zh** [comment]
@maria-vslvn , great job.
Some minor issues: 
1.  Header column names should have font size 14 px, font-weight = normal in the 'Your Orders' table (should match to the Auctions list table)
2. when select 30 items per page in the Auctions list table, them flip pages, grid is not auto-scrolled to the top. 
Could you please fix it? 

Also, @cmagan , could you please take a look at the Auctions list table and tell if it looks good for you when more than 5 lines per page are selected in the pagination?

Thanks

**Comment by maria-vslvn** [comment]
@elena-zh fixed

**Comment by cmagan** [comment]
Hey, @elena-zh @maria-vslvn 
Happy that we were able to transform all table into tables with headers instead of description at every line. 
It looks clean!
I agree that it'd be good if when scrolling pages in a table, it'd always go to the top of the table - but not super important if there are issues with this

Aside from this it looks great

**Comment by elena-zh** [comment]
@maria-vslvn , the issue with auto-scrolling the table to the top is still here: https://drive.google.com/file/d/1RmuZKPqF0uYa5Z2FH1PdE6i6epmRHxlD/view

Could you please fix it?

**Comment by maria-vslvn** [comment]
@elena-zh please check

**Comment by elena-zh** [comment]
@maria-vslvn , could you please move tasks to the Review column once they are ready for me to test?
Thanks

**Comment by elena-zh** [comment]
Great! All changes look good to me now. 
Thank you

**Review by josojo — APPROVED** [review]
LGTM. Thanks

**Pull request merged**
