### PR TITLE
[issue-379] xdai gas price is not always set correctly

### PR DESCRIPTION
**Pull request by jarcodallo**
image

image

### CODE REVIEW

**Comment by josojo** [comment]
Will thiss PR change the behaviour on mainnet? What is the gas price on mainnet?

It would be great to have also a solution for approval and claiming txs

**Comment by jarcodallo** [comment]
@josojo ready for review

**Review by mariano-aguero — APPROVED** [review]

**Comment by josojo** [comment]
Reverting just to be super cautious and to not risk disturbing the sale. Actually, the code is looking good!

**Comment by elena-zh** [comment]
Re-opened as changes were reverted in #472 pr.

**Pull request merged**
