### PR TITLE
Feature/#479 mob menu issue

### PR DESCRIPTION
**Pull request by maria-vslvn**
mobile menu was made fixed, also top disclaimer was moved under the main scroll wrap in order to make an indent for fixed header
fixed: part of orderbook chart is truncated on mobiles

### CODE REVIEW

**Comment by maria-vslvn** [comment]
@elena-zh 
[](url)https://images.zenhubusercontent.com/326940559/4359eca9-7237-4263-b053-7c8c1ca663d3/video_2021_06_29_13_34_33.mp4

**Comment by elena-zh** [comment]
Hi @maria-vslvn, @ramirotw  , could you please enable a PR preview link?

**Comment by ramirotw** [comment]
@maria-vslvn when starting a new ticket in a new branch I'd suggest to do the following so you don't pick the wrong commits as with the `renaming deployments` which prevents Github Actions to run the deployment script:

```bash
git fetch
git checkout -b feature/#479-mob-menu-issue origin/develop
```

This will ensure to always fetch the latest changes from origin and then create the branch from the latest commit.

**Comment by elena-zh** [comment]
Hi @josojo , seems that deployment has failed=(

**Comment by josojo** [comment]
@elena-zh did you have chance to fix it? It's just one linting error? You can see it in the logs of the failed build

**Comment by maria-vslvn** [comment]
@elena-zh @josojo  fixed

**Comment by elena-zh** [comment]
Hi @maria-vslvn , 
changes LGTM: menu does not overlap page's content now. 
App's header is also always visible now. 
However, top content of an auction details page is still not fully visible. I have updated the #733 issue description about this case. 

Thanks

**Pull request merged**
