### PR TITLE
visible theme issues fixed

### LINKED ISSUE #803: Themes issues
There are issues on Auctions caused by applying static light or dark colors throughout the app, here are examples below:

### PR DESCRIPTION
**Pull request by maria-vslvn**
Closes #803 
color styles are passed now as dynamic props depending on theme

### CODE REVIEW

**Comment by elena-zh** [comment]
One UI issues in this PR: auctions filter value is in blue (should be in white)
image

**Comment by maria-vslvn** [comment]
@elena-zh please check

**Comment by elena-zh** [comment]
now changes LGTM

**Comment by josojo** [comment]
Thanks for checking

**Pull request merged**
