### PR TITLE
(Fix) Tooltips z-index

### LINKED ISSUE #576: Tooltips to be fixed

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #576 

This should fix all the problems with the tooltips' z-index.

@maria-vslvn last PR added some new tooltips and I fixed those too, so I'm merging this PR into the branch she created to avoid having to fix more tooltips later.

### CODE REVIEW

**Review by henrypalacios — APPROVED** [review]
Great, I just have one doubt, on mobile the tooltip remains pressed, is this the expected behavior?

Selection_286

**Comment by gabitoesmiapodo** [comment]
> Great, I just have one doubt, on mobile the tooltip remains pressed, is this the expected behavior?
> 
> Selection_286

I'd expect it to behave as it does originally on the base plugin, but I don't know.

Anyway, it may be a problem to be fixed on another issue.

**Review by josojo — APPROVED** [review]
LGTM

**Comment by elena-zh** [comment]
LGTM

**Review by ramirotw — APPROVED** [review]

**Pull request merged**
